// Copyright 2011-2012 Paulo Augusto Peccin. See licence.txt distributed with this file.

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_joy_JoyInterface */

#ifndef _Included_org_joy_JoyInterface
#define _Included_org_joy_JoyInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_joy_JoyInterface
 * Method:    getMaxDevices
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_joy_JoyInterface_getMaxDevices
  (JNIEnv *, jclass);

/*
 * Class:     org_joy_JoyInterface
 * Method:    isConnected
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_joy_JoyInterface_isConnected
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_joy_JoyInterface
 * Method:    updateInfo
 * Signature: (ILorg/joy/Joy/Info;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_joy_JoyInterface_updateInfo
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_joy_JoyInterface
 * Method:    updateState
 * Signature: (ILorg/joy/Joy/State;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_joy_JoyInterface_updateState
  (JNIEnv *, jclass, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
